rvm:
  - 1.9.3
bundler_args: --without development
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "rake test\\[standard]"
notifications:
  webhooks: http://emberjs-master-builds.herokuapp.com/upload/ember.js
branches:
  except:
    - latest-builds
    - release-builds
